# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_a5R_wrappers", use_symbols = TRUE, package_name = "a5R")

#' @usage NULL
#' @useDynLib a5R, .registration = TRUE
NULL

a5_set_threads_rs <- function(n) invisible(.Call(wrap__a5_set_threads_rs, n))

a5_get_threads_rs <- function() .Call(wrap__a5_get_threads_rs)

#' Convert longitude/latitude coordinates to A5 cell indices.
#'
#' Vectorised over `lon`, `lat`, and `resolution`.
#'
#' @param lon Numeric vector of longitudes (degrees).
#' @param lat Numeric vector of latitudes (degrees).
#' @param resolution Integer vector of resolutions (0--30).
#' @return A character vector of cell IDs (hex-encoded).
#' @noRd
#' @keywords internal
a5_lonlat_to_cell_rs <- function(lon, lat, resolution) .Call(wrap__a5_lonlat_to_cell_rs, lon, lat, resolution)

#' Convert A5 cell indices to longitude/latitude coordinates.
#'
#' @param cell Character vector of hex-encoded cell IDs.
#' @param normalise Logical: if TRUE, wrap longitudes to the standard range.
#' @return A list with `lon` and `lat` numeric vectors.
#' @noRd
#' @keywords internal
a5_cell_to_lonlat_rs <- function(cell, normalise) .Call(wrap__a5_cell_to_lonlat_rs, cell, normalise)

#' Get boundary polygons for A5 cells as WKT strings.
#'
#' @param cell Character vector of hex-encoded cell IDs.
#' @param closed_ring Logical: should the polygon ring be closed?
#' @param segments Integer: number of interpolation segments per edge.
#' @return A character vector of WKT POLYGON strings.
#' @noRd
#' @keywords internal
a5_cell_to_boundary_rs <- function(cell, closed_ring, segments) .Call(wrap__a5_cell_to_boundary_rs, cell, closed_ring, segments)

#' Get boundary polygons for A5 cells as WKB raw vectors.
#'
#' @param cell Character vector of hex-encoded cell IDs.
#' @param closed_ring Logical: should the polygon ring be closed?
#' @param segments Integer: number of interpolation segments per edge.
#' @return A list of raw vectors (WKB bytes) or NULL for NA cells.
#' @noRd
#' @keywords internal
a5_cell_to_boundary_wkb_rs <- function(cell, closed_ring, segments) .Call(wrap__a5_cell_to_boundary_wkb_rs, cell, closed_ring, segments)

#' Get the area (in square metres) of cells at a given resolution.
#'
#' @param resolution Integer vector of resolutions (0--30).
#' @return Numeric vector of areas in square metres.
#' @noRd
#' @keywords internal
a5_cell_area_rs <- function(resolution) .Call(wrap__a5_cell_area_rs, resolution)

#' Get total number of cells at a given resolution.
#'
#' @param resolution Integer scalar (0--30).
#' @return Numeric scalar (as double, since R has no u64).
#' @noRd
#' @keywords internal
a5_get_num_cells_rs <- function(resolution) .Call(wrap__a5_get_num_cells_rs, resolution)

#' Validate hex cell IDs.
#'
#' @param cell Character vector of hex strings to validate.
#' @return Logical vector indicating validity.
#' @noRd
#' @keywords internal
a5_is_valid_cell_rs <- function(cell) .Call(wrap__a5_is_valid_cell_rs, cell)

#' Get the resolution of A5 cell indices.
#'
#' @param cell Character vector of hex-encoded cell IDs.
#' @return Integer vector of resolutions.
#' @noRd
#' @keywords internal
a5_get_resolution_rs <- function(cell) .Call(wrap__a5_get_resolution_rs, cell)

#' Navigate to parent cell(s).
#'
#' @param cell Character vector of hex-encoded cell IDs.
#' @param parent_resolution Integer: target parent resolution. NULL for
#'   immediate parent.
#' @return Character vector of hex-encoded parent cell IDs.
#' @noRd
#' @keywords internal
a5_cell_to_parent_rs <- function(cell, parent_resolution) .Call(wrap__a5_cell_to_parent_rs, cell, parent_resolution)

#' Get child cells.
#'
#' @param cell A single hex-encoded cell ID.
#' @param child_resolution Integer: target child resolution. NULL for
#'   immediate children.
#' @return Character vector of hex-encoded child cell IDs.
#' @noRd
#' @keywords internal
a5_cell_to_children_rs <- function(cell, child_resolution) .Call(wrap__a5_cell_to_children_rs, cell, child_resolution)

#' Get all 12 resolution-0 root cells.
#'
#' @return Character vector of 12 hex-encoded cell IDs.
#' @noRd
#' @keywords internal
a5_get_res0_cells_rs <- function() .Call(wrap__a5_get_res0_cells_rs)

#' Compact a set of A5 cell IDs.
#'
#' Merges sibling groups into their common parent.
#'
#' @param cells Character vector of hex-encoded cell IDs.
#' @return Character vector of compacted hex-encoded cell IDs.
#' @noRd
#' @keywords internal
a5_compact_rs <- function(cells) .Call(wrap__a5_compact_rs, cells)

#' Uncompact a set of A5 cell IDs to a target resolution.
#'
#' @param cells Character vector of hex-encoded cell IDs.
#' @param target_resolution Integer: the resolution to expand to.
#' @return Character vector of uncompacted hex-encoded cell IDs.
#' @noRd
#' @keywords internal
a5_uncompact_rs <- function(cells, target_resolution) .Call(wrap__a5_uncompact_rs, cells, target_resolution)

#' Generate a grid of A5 cells covering a bounding box.
#'
#' Uses hierarchical descent with bbox filtering entirely in Rust.
#'
#' @param xmin,ymin,xmax,ymax Bounding box coordinates.
#' @param resolution Target resolution (0--30).
#' @return Character vector of hex-encoded cell IDs.
#' @noRd
#' @keywords internal
a5_grid_bbox_rs <- function(xmin, ymin, xmax, ymax, resolution) .Call(wrap__a5_grid_bbox_rs, xmin, ymin, xmax, ymax, resolution)

#' Filter cell IDs to those whose boundary polygons intersect a target geometry.
#'
#' @param cells Character vector of hex-encoded cell IDs.
#' @param target_wkt WKT string of the target geometry.
#' @return Character vector of cell IDs that intersect the target.
#' @noRd
#' @keywords internal
a5_grid_intersects_rs <- function(cells, target_wkt) .Call(wrap__a5_grid_intersects_rs, cells, target_wkt)

#' Get all cells within k hops of a centre cell.
#'
#' @param cell A single hex-encoded cell ID.
#' @param k Number of hops.
#' @param vertex If TRUE, include vertex-sharing (8-connected) neighbours.
#' @return Character vector of hex-encoded cell IDs.
#' @noRd
#' @keywords internal
a5_grid_disk_rs <- function(cell, k, vertex) .Call(wrap__a5_grid_disk_rs, cell, k, vertex)

#' Get all cells within a great-circle radius of a centre cell.
#'
#' @param cell A single hex-encoded cell ID.
#' @param radius Great-circle radius in metres.
#' @return Character vector of hex-encoded cell IDs.
#' @noRd
#' @keywords internal
a5_spherical_cap_rs <- function(cell, radius) .Call(wrap__a5_spherical_cap_rs, cell, radius)


# nolint end
